name: Auto-Incrementing Keysubtracter Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # हर घंटे चलाएँ

jobs:
  keysubtracter_job:
    runs-on: ubuntu-latest

    steps:
    - name: रिपॉजिटरी चेकआउट करें
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Git कॉन्फ़िगर करें
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: आवश्यक टूल्स इंस्टॉल करें
      run: sudo apt update && sudo apt install -y make gcc

    - name: Keysubtrac और Ecctools क्लोन और बिल्ड करें
      run: |
        git clone https://github.com/Ramavatar98/keysubtrac.git
        cd keysubtrac
        make
        git clone https://github.com/Ramavatar98/ecctools.git
        cd ecctools
        make
        cp keymath ../

    - name: `counter.txt` तैयार करें
      run: |
        cd keysubtrac
        if [ ! -f counter.txt ]; then echo "10" > counter.txt; fi

    - name: मुख्य लॉजिक निष्पादित करें
      run: |
        cd keysubtrac
        n=$(cat counter.txt)
        new_n=$((n + 10))
        echo "$new_n" > counter.txt

        pubkey="03d133ef106358489f8f976dc4b6c5469921e3dfe36f326dc9f05387579d444e6a"
        checked=()
        minus_count=0
        round_num=0

        while true; do
          round_num=$((round_num + 1))
          echo "[Round $round_num] Using PubKey: $pubkey with -n $new_n"

          ./keysubtracter -p "$pubkey" -n "$new_n" -x -b 12 > result1.txt
          half_pubkey=$(./keymath "$pubkey" / 2)
          ./keysubtracter -p "$half_pubkey" -n "$new_n" -x -b 11 > result2.txt

          match=$(comm -12 <(sort result1.txt) <(sort result2.txt))
          if [ ! -z "$match" ]; then
            echo "[✓] Match Found after $minus_count x '-1' operations!"
            echo "Match found after $minus_count x '-1'" > match_found.txt
            echo "Main pubkey used: $pubkey" >> match_found.txt
            echo "Half pubkey used: $half_pubkey" >> match_found.txt
            echo "Matched lines:" >> match_found.txt
            echo "$match" >> match_found.txt
            break
          fi

          new_pubkey=$(./keymath "$pubkey" - 1)

          if [[ " ${checked[@]} " =~ " ${new_pubkey} " ]]; then
            echo "[x] Already tried this pubkey. Ending loop."
            break
          fi

          checked+=("$pubkey")
          pubkey="$new_pubkey"
          minus_count=$((minus_count + 1))
        done

    - name: परिणाम कमिट करें
      run: |
        cd keysubtrac
        git pull
        git add counter.txt match_found.txt || true
        git commit -m "Update counter to $new_n and add match results" || true
        git push
        
